export const Images = {
    LOGO_Image: require('../Assets/Images/Logo/logo.png'),
    BackBuuton: require('../Assets/Images/Backbutton/backbutton.png'),
    Splash_logo: require('../Assets/Images/SplashLogo/splashLogo.png'),
    WELCOME_1: require('../Assets/Images/Welcome1/welcome.png'),
    WELCOME_2: require('../Assets/Images/welcome2/welcome2.png'),
    WELCOME_3: require('../Assets/Images/Welcome3/welcome3.png'),
    SALOON_TYPES: require('../Assets/Images/Saloontype/saloontype.png'),
    SALOON_TYPE: require('../Assets/Images/Seasor/seasor.png'),
    USER_TYPE: require('../Assets/Images/TypeUser/user.png'),
    BottomHome: require('../Assets/Images/home/home.png'),
    BottomScissor: require('../Assets/Images/bottomseasor/bottomseasor.png'),
    BottomUsers: require('../Assets/Images/bottomUsers/bottomUsers.png'),
    BottomUserIcon: require('../Assets/Images/bottomUserIcon/bottomUserIcon.png'),
    kycForm: require('../Assets/Images/kycform/kycform.png'),
    Notification: require('../Assets/Images/notification/notification.png'),
    NotificationUser: require('../Assets/Images/notificationUser/notificationUser.png'),
    SIGN_IN_LOCATION: require("../Assets/Images/SignupLocation/Group33300.png"),
    HOME_BANNER: require("../Assets/Images/bannerImage/bannerImage.png"),
    SEARCH_ICON: require("../Assets/Images/searchIcon/searchIcon.png"),
    CHOTI_DESIGN: require('../Assets/Images/chotiDesign/chotiDesign.png'),
    BOTTOM_CART: require('../Assets/Images/BottomCart/BottomCart.png'),
    BOTTOM_BOOKING: require('../Assets/Images/BottomBooking/BottomBooking.png'),
    LOCATION: require('../Assets/Images/Location/Location.png'),
    HAIRCUTTINGS: require('../Assets/Images/haircutting/haircutting.png'),
    LOCATION_DETECT: require('../Assets/Images/locationDetect/locationDetect.png'),
    CROSS_ICONS: require('../Assets/Images/crossIcon/crossIcon.png'),
    USERS_ADS: require('../Assets/Images/userAds/userAds.png'),
    SALLON_BG_IMAGE: require('../Assets/Images/sallonbgImage/sallonbgImage.png'),
    UNLIKE: require('../Assets/Images/unlike/unlike.png'),
    STAR: require('../Assets/Images/star/star.png'),
    EDIT: require('../Assets/Images/edit/edit.png'),
    LOGIN_USER_IMAGE: require('../Assets/Images/personImage/personImage.png'),
    CONTACTUSIMAGE: require('../Assets/Images/contactUs/contactUs.png'),
    Mobile_phone: require('../Assets/Images/mobilePhone/mobilePhone.png'),
    Whatsapp: require('../Assets/Images/whatsapp/whatsapp.png'),
    Instagram: require('../Assets/Images/instagrma/instagrma.png'),
    Facebook: require('../Assets/Images/facebook/facebook.png'),
    Twitter: require('../Assets/Images/twitter/twitter.png'),
    Profit: require('../Assets/Images/profit/profit.png'),
    EMAIL: require('../Assets/Images/mail/mail.png'),
    UniIcon: require('../Assets/Images/uniIcon/uniIcon.png'),
    BookingUserIcon: require('../Assets/Images/bookingUserIcon/bookingUserIcon.png'),
    AC: require('../Assets/Images/ac/ac.png'),
    TV: require('../Assets/Images/tv/tv.png'),
    Sofa: require('../Assets/Images/sofa/sofa.png'),
    Newspaper: require('../Assets/Images/newspaper/newspaper.png'),
    Magzine: require('../Assets/Images/magzine/magzine.png'),
    SaloonUser: require('../Assets/Images/saloonUser/saloonUser.png'),
    SaloonBgGallery: require('../Assets/Images/saloonBgGallery/saloonBgGallery.png'),
    BGBack: require('../Assets/Images/bgBack/bgBack.png'),
    NoInternet: require('../Assets/Images/Nointernet/Nointernet.png'),
    ContactIcon: require('../Assets/Images/contactIcon/contactIcon.png'),
    QR_SCAN_ICON: require('../Assets/Images/qrScan/qrScan.png'),
    MAP_ICON: require('../Assets/Images/mapLocation/mapLocation.png'),
    RefreshIcon: require('../Assets/Images/refreshIcon/refreshIcon.png'),
    Booking_Ads: require('../Assets/Images/bookingAds/bookingAds.png'),
    QRCODE_CORRECT: require('../Assets/Images/rightClick/rightClick.png'),
    QRCODE_WRONG: require('../Assets/Images/wrongClick/wrongClick.png'),
    Key:require('../Assets/Images/key/key.png'),
    NotificatioIcon:require('../Assets/Images/notificationIcon/notificationIcon.png'),
    ArrowKey:require('../Assets/Images/arrowKey/arrowKey.png'),
    USER_DELETE:require('../Assets/Images/userDelete/userDelete.png'),
    ForgotMpin_bg:require('../Assets/Images/forgotPinbg/forgotPinbg.png'),
    SaloonIcon:require('../Assets/Images/barberShop/barberShop.png'),
    BarberSales:require('../Assets/Images/barberSales/barberSales.png'),
    BarberIcon:require('../Assets/Images/barberIcon/barberIcon.png'),
    CustomerIcon:require('../Assets/Images/customerIcon/customerIcon.png'),
    Timer:require('../Assets/Images/timer/timer.png'),
    CustomerList:require('../Assets/Images/customerList/customerList.png'),
    pending:require('../Assets/Images/pendingList/pendingList.png'),
    CompleteList:require('../Assets/Images/completeList/completeList.png'),
    CancelList:require('../Assets/Images/cancelList/cancelList.png'),
    BarberBG:require('../Assets/Images/barberBg/barberBg.png'),
    CustomerBg:require('../Assets/Images/customerBg/customerBg.png'),
    SalesBG:require('../Assets/Images/salesBg/salesBg.png'),
    FeedBackBg:require('../Assets/Images/feedbackBg/feedbackBg.png'),
    Saloonrefer:require('../Assets/Images/saloonrefer/saloonrefer.png'),
    AddPlus:require('../Assets/Images/addPlus/addPlus.png'),
    ConfirmNotification:require('../Assets/Images/confirmNotification/confirmNotification.png'),
    ConfirmLogout:require('../Assets/Images/confirmlogout/confirmlogout.png'),
    ConfirmUser:require('../Assets/Images/user/user.png'),
    Check:require('../Assets/Images/check/check.png'),
    UnCheck:require('../Assets/Images/uncheck/uncheck.png'),
    SORT:require('../Assets/Images/sort/sort.png'),
    clock:require('../Assets/Images/clock/clock.png'),
    SloonOrder:require('../Assets/Images/saloonOrder/saloonOrder.png'),
    SaloonComplete:require('../Assets/Images/saloonComplete/saloonComplete.png'),
    SaloonCancel:require('../Assets/Images/saloonCancel/saloonCancel.png'),
    saloonPending:require('../Assets/Images/saloonPending/saloonPending.png'),
    TodaySales:require('../Assets/Images/todaySales/todaySales.png'),
    SalesIcons:require('../Assets/Images/salesIcons/salesIcons.png'),

}