export const Routes = {
    Splash: 'Splash',
    Signin: 'Signin',
    Signup: 'Signup',
    Welcome: 'Welcome',
    CreatePin: 'CreatePin',
    ChooseType: 'ChooseType',
    Barber: 'Barber',
    User: 'user',
    BarberHome: 'Home',
    BarberOrders: 'Orders',
    BarberSaloon: 'My Salons',
    BarberProfile: 'Profile',
    TrendingList: 'TrendingList',
    TrendingDetails: 'TrendingDetails',
    UserHome: 'Home',
    UserSearch: 'Search',
    UserBookings: 'Booking',
    UserCart: 'Cart',
    UserProfile: 'Profile',
    ContactUs: 'contactus',
    AppVersion: 'appversion',
    FeedBack: 'feedback',
    Reviews: 'Reviews',
    PrivacyPolicy: 'privacypolicy',
    UserBooking: 'userBooking',
    UserFavouriteSaloon: 'userfavouritesaloon',
    ReferEarn: 'referEarn',
    UserBookingSaloon: 'userbookingsaloon',
    UserSaloonDetails: 'userSaloonDetails',
    UserReviewList: 'UserReviewList',
    UserRecommendedBarber: 'UserRecommendedBarber',
    SaloonBookingScreen: 'SaloonBookingScreen',
    UserServices: 'UserServices',
    SaloonGallery: 'SaloonGallery',
    UserLocationMap: "UserLocationMap",
    UserBookingComplete: 'UserBookingComplete',
    UserQrScanner: 'UserQrScanner',
    EditUserScreen: "EditUserScreen",
    ProfileDetials: 'ProfileDetials',
    UserNotification: 'UserNotification',
    ForgotMpin: 'ForgotMpin',
    SaloonAddCustomer: 'SaloonAddCustomer',
    SaloonCustomerDetailPage: 'SaloonCustomerDetailPage',
    SaloonCustomerList: 'SaloonCustomerList',
    SaloonDetailsPage: 'SaloonDetailsPage',
    SaloonQrCode: 'SaloonQrCode',
    BarberPrivacyPolicy: 'BarberPrivacyPolicy',
    SaloonBarberReferAndEarn: 'SaloonBarberReferAndEarn',
    SaloonAddBarber: 'SaloonAddBarber',
    SaloonAddServices: 'SaloonAddServices',
    SaloonBarberDetialPage: 'SaloonBarberDetialPage',
    SaloonBarberList: 'SaloonBarberList',
    SaloonEditProfile: 'SaloonEditProfile',
    SaloonFeedback: 'SaloonFeedback',
    SaloonNotification: 'SaloonNotification',
    SaloonNotificationLists: 'SaloonNotificationLists',
    SaloonServices: 'SaloonServices',
    SaloonContactUs: 'SaloonContactUs',
    BarberProfileDetails: 'BarberProfileDetails',
    SaloonChangePassword: 'SaloonChangePassword',
    EditSaloonDetails: 'EditSaloonDetails',
    SaloonKycDetails: 'SaloonKycDetails',
    AddSaloonkycDetails: 'AddSaloonkycDetails',
    AddBarberList: 'AddBarberList',
    AddUnisexServices: 'AddUnisexServices',
    BarberEditPage: 'BarberEditPage',
    SaloonMySaloonPage:'SaloonMySaloonPage',
    SaloonSales:'SaloonSales',
    AtricalDetails:'AtricalDetails',
    UserSignup:'UserSignup',
    ArticalList:'ArticalList',
    CategoryDetails:'categoryDetails',
    CategoryList:'categoryList',


}