export const TextConstant = {
    SplashText: 'At Dizi Salon, we believe that beauty is an art form, and each individual is a masterpiece waiting to be unveiled. Our passion for creativity and innovation drives us to deliver personalized services that accentuate your unique features and let your inner beauty shine.',
    WELCOME_1_DESC: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    WELCOME_2_DESC: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    WELCOME_3_DESC: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    FOR_SALOON: 'For Salon',
    FOR_USER: 'For User',
    //Sign In Texts
    SignIn_heading: "Sign in",
    SignIn_subHeading: "Welcome! Please enter your details",
    SignIn_label_one: "Mobile Number",
    SignIn_placeholder_one: "Mobile Number",
    SignIn_label_two: "Enter MPIN",
    SignIn_placeholder_two: "Enter MPIN",
    signIn_bottomInfoText_left_one: "Are you a New User?",
    signIn_bottomInfoText_left_two: "Please Sign up!",
    signIn_bottomInfoText_right: "Forgot MPIN?",
    //Sign Up Texts
    SignUp_heading: "Sign Up",
    SignUp_subHeading: "Greeting From DiZi Salon!",
    SignUp_label_one: "Salon Owner Name*",
    SignUp_placeholder_one: "e.g., John Doe",
    SignUp_label_two: "Salon Name*",
    SignUp_placeholder_two: "e.g., DiZi Salon",
    signUp_label_three: "Phone Number*",
    signUp_label_five: "E-Mail Address*",
    Signup_address:'Address',
    create_pin_heading: "Create MPIN",
    create_pin_subheading: "Greeting From DiZi Salon!",
    create_pin_label_one: "New MPIN",
    create_pin_label_two: "Confirm MPIN",
    Phone_number: 'Phone Number*',
    OTP_NUMBER: 'Fill OTP that come in your phone',
    KYC_MAIN_TEXT: 'Let’s do KYC and List your Salon',
    KNOW_MORE: 'Know More',
    LIST_NOW: 'List Now',
    TRENDING_STYLE: 'Trending Style’s',
    SHOW_MORE: 'Show More',
    SEARCH_TEXT: 'Search for Styles',
    CHOTI_Title: 'Chotli Braid',
    LOCATION: 'Location',
    CATEGORIES: 'Categories',
    SEARCH_NEAR_SALON: 'Search Nearest Salon',
    LOCATION_TITLE: 'Hey there! Where are you?',
    LOCATION_SUB_TITLE: 'Don’t miss out this. Please select your location.',
    DETECT_LOCATION: 'Detect My Location',
    LOCATION_MANUALLY: 'Select Manually',
    USER_ADS_TEXT: "Don't Know which Hair Style looks good on you ",
    CART: 'Cart (4)',
    ADD_SERVICES: 'Add Service',
    CHECKOUT:'Checkout (4)',
    SEARCH_FOR_SERVICE:'Search for Service',
    SEARCH__HAIR_CUTTING_SALON:'Search “Hair cutting salon”',
    EDIT:'Edit',
    REFEREARN:'Refer & Earn',
    CONTACTUS:'Contact Us',
    NAME:'Name*',
    NamePlace:'e.g., John Doe',
    Submit:'Submit',
    MESSAGESUCCESSFULLY:'You have successfully sent your message',
   Continue :'Continue',
   TOTAL_POINTS:'Total Points',
   SHARE_EMAIL:'Share via email',
   Send:'send',
   ENTER_EMAIL:'Enter E-Mail Address',
   SHARE_WITH_FAMILY:"Share with family",
   Member:'Members',
   SHARE_SOCAIL_TEXT:'Share via social media',
   PRIVACY_POLICY:'Privacy Policy',
   AUTH_USER:'Authorized User',
   MY_BOOKING:'My Booking',
   Gallery:'Gallery',
   BeforeLunch:'Before <Lunch Time>',
   AfterLunch:'After <Lunch Time>',
   NO_Connection :'No Connection',
   NO_Connection_Desc:'Please Check Your internet connection.',
   Confirm_Book:"Confirm Book",
   Confirm_subBook:'Confirm Booking to allocate the slot at salon!',
   Confirm:'Confirm',
   Completed:'Completed',
   SCAN_AGAIN:'Scan Again'
}